# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "818ba4802638073b28c2096edf20c419"
name = "bundle-theme-test"
handle = "bundle-theme-test"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
